default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sportphotoz_development

test:
  <<: *default
  database: sportphotoz_test

production:
  <<: *default
  database: sportphotoz_production
  username: sportphotoz
  password: <%= ENV['SPORTPHOTOZ_DATABASE_PASSWORD'] %>
